### ISSUE TITLE
The taps in the sky130_fd_sc_hd__tap_2 cell aren't connected.

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/skywater-pdk-libs-sky130_fd_sc_hd#19]
<img width="800" alt="tap_2" src="https://github.com/efabless/skywater-pdk-libs-sky130_fd_sc_hd/assets/8349634/c298bf3c-248a-46b4-a4e4-6aca1564fae4">

**Comment by RTimothyEdwards** [comment]
Yes, these are "do-it-yourself" tap connections.  `tapvpwrvgnd` has the connections inside the cell;  other tap cells have only one of the connections, or none.  I assume there are use cases for them, probably where you want to connect well or substrate to an isolated power or ground.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards Yeah, thinking about it, I came to the same conclusion. Sometimes you don't want the source and bulk connections to be the same.
